services:
  - type: web
    name: fastapi-mysql-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: HOST
        value: your_host
      - key: USER
        value: your_user
      - key: PASSWORD
        value: your_password
      - key: DATABASE
        value: your_database
